version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:80"
        depends_on:
            - db
        environment:
            # TYPEORM_CONNECTION: "postgres"
        #     TYPEORM_HOST: "db"
        #     TYPEORM_USERNAME: "postgres"
        #     TYPEORM_PASSWORD: "mysecretpassword"
        #     # TYPEORM_URL: "postgres://postgres:mysecretpassword@db:5432/nestjsrealworld"
        #     TYPEORM_URL: "${DATABASE_URL}"
        #     TYPEORM_DATABASE: "nestjsrealworld"
        #     TYPEORM_PORT: "5432"
        #     TYPEORM_SYNCHRONIZE: "true"
        #     TYPEORM_LOGGING: "true"
        #     TYPEORM_ENTITIES: "./**/**.entity.js"
            DATABASE_URL: "postgres://postgres:mysecretpassword@db:5432/nestjsrealworld"
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: "mysecretpassword"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "nestjsrealworld"