# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    env:
      DATABASE_URL: "postgres://postgres:mysecretpassword@localhost:5432/nestjsrealworld"
      NODE_ENV: test

    strategy:
      # Allow a version of node to fail and still carry on testing the others
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - name: copy the config module
      run: cp src/config.ts.example src/config.ts
    - name: Compile the application
      run: npm run prestart:prod

    - run: docker-compose build
    - run: docker-compose up -d
    - name: show state of containers
      run: docker ps -a

    - run: npm run test:coverage -- --forceExit
    - run: npm run test -- --forceExit
